# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='transmission.proto',
  package='transmission',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12transmission.proto\x12\x0ctransmission\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x01\",\n\x06Matrix\x12\"\n\x04rows\x18\x01 \x03(\x0b\x32\x14.transmission.Vector\"6\n\x0bMachineInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"g\n\x0b\x44ictValNote\x12\x15\n\ris_list_value\x18\x01 \x01(\x08\x12\x11\n\tbuff_type\x18\x02 \x01(\x05\x12\x16\n\x0e\x62uff_start_ind\x18\x03 \x01(\x05\x12\x16\n\x0eval_elm_amount\x18\x04 \x01(\x05\"\xb2\x03\n\rReqResMessage\x12\x36\n\x13source_machine_info\x18\x01 \x01(\x0b\x32\x19.transmission.MachineInfo\x12\x36\n\x13target_machine_info\x18\x02 \x01(\x0b\x32\x19.transmission.MachineInfo\x12\x11\n\tphase_num\x18\x03 \x01(\t\x12\x13\n\x0bmulti_bytes\x18\x04 \x03(\x0c\x12&\n\x08matrices\x18\x05 \x03(\x0b\x32\x14.transmission.Matrix\x12%\n\x07vectors\x18\x06 \x03(\x0b\x32\x14.transmission.Vector\x12\x0e\n\x06values\x18\x07 \x03(\x01\x12\x0f\n\x07strings\x18\x08 \x03(\t\x12\x0c\n\x04ints\x18\t \x03(\x05\x12>\n\ndict_notes\x18\n \x03(\x0b\x32*.transmission.ReqResMessage.DictNotesEntry\x1aK\n\x0e\x44ictNotesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.transmission.DictValNote:\x02\x38\x01\x32R\n\x0cTransmission\x12\x42\n\x04\x63omm\x12\x1b.transmission.ReqResMessage\x1a\x1b.transmission.ReqResMessage\"\x00\x62\x06proto3'
)




_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='transmission.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='transmission.Vector.values', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=60,
)


_MATRIX = _descriptor.Descriptor(
  name='Matrix',
  full_name='transmission.Matrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='transmission.Matrix.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=106,
)


_MACHINEINFO = _descriptor.Descriptor(
  name='MachineInfo',
  full_name='transmission.MachineInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='transmission.MachineInfo.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='transmission.MachineInfo.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='transmission.MachineInfo.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=162,
)


_DICTVALNOTE = _descriptor.Descriptor(
  name='DictValNote',
  full_name='transmission.DictValNote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_list_value', full_name='transmission.DictValNote.is_list_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buff_type', full_name='transmission.DictValNote.buff_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buff_start_ind', full_name='transmission.DictValNote.buff_start_ind', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val_elm_amount', full_name='transmission.DictValNote.val_elm_amount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=267,
)


_REQRESMESSAGE_DICTNOTESENTRY = _descriptor.Descriptor(
  name='DictNotesEntry',
  full_name='transmission.ReqResMessage.DictNotesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='transmission.ReqResMessage.DictNotesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='transmission.ReqResMessage.DictNotesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=704,
)

_REQRESMESSAGE = _descriptor.Descriptor(
  name='ReqResMessage',
  full_name='transmission.ReqResMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_machine_info', full_name='transmission.ReqResMessage.source_machine_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_machine_info', full_name='transmission.ReqResMessage.target_machine_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phase_num', full_name='transmission.ReqResMessage.phase_num', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='multi_bytes', full_name='transmission.ReqResMessage.multi_bytes', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matrices', full_name='transmission.ReqResMessage.matrices', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vectors', full_name='transmission.ReqResMessage.vectors', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='transmission.ReqResMessage.values', index=6,
      number=7, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strings', full_name='transmission.ReqResMessage.strings', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ints', full_name='transmission.ReqResMessage.ints', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dict_notes', full_name='transmission.ReqResMessage.dict_notes', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_REQRESMESSAGE_DICTNOTESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=704,
)

_MATRIX.fields_by_name['rows'].message_type = _VECTOR
_REQRESMESSAGE_DICTNOTESENTRY.fields_by_name['value'].message_type = _DICTVALNOTE
_REQRESMESSAGE_DICTNOTESENTRY.containing_type = _REQRESMESSAGE
_REQRESMESSAGE.fields_by_name['source_machine_info'].message_type = _MACHINEINFO
_REQRESMESSAGE.fields_by_name['target_machine_info'].message_type = _MACHINEINFO
_REQRESMESSAGE.fields_by_name['matrices'].message_type = _MATRIX
_REQRESMESSAGE.fields_by_name['vectors'].message_type = _VECTOR
_REQRESMESSAGE.fields_by_name['dict_notes'].message_type = _REQRESMESSAGE_DICTNOTESENTRY
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['Matrix'] = _MATRIX
DESCRIPTOR.message_types_by_name['MachineInfo'] = _MACHINEINFO
DESCRIPTOR.message_types_by_name['DictValNote'] = _DICTVALNOTE
DESCRIPTOR.message_types_by_name['ReqResMessage'] = _REQRESMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'transmission_pb2'
  # @@protoc_insertion_point(class_scope:transmission.Vector)
  })
_sym_db.RegisterMessage(Vector)

Matrix = _reflection.GeneratedProtocolMessageType('Matrix', (_message.Message,), {
  'DESCRIPTOR' : _MATRIX,
  '__module__' : 'transmission_pb2'
  # @@protoc_insertion_point(class_scope:transmission.Matrix)
  })
_sym_db.RegisterMessage(Matrix)

MachineInfo = _reflection.GeneratedProtocolMessageType('MachineInfo', (_message.Message,), {
  'DESCRIPTOR' : _MACHINEINFO,
  '__module__' : 'transmission_pb2'
  # @@protoc_insertion_point(class_scope:transmission.MachineInfo)
  })
_sym_db.RegisterMessage(MachineInfo)

DictValNote = _reflection.GeneratedProtocolMessageType('DictValNote', (_message.Message,), {
  'DESCRIPTOR' : _DICTVALNOTE,
  '__module__' : 'transmission_pb2'
  # @@protoc_insertion_point(class_scope:transmission.DictValNote)
  })
_sym_db.RegisterMessage(DictValNote)

ReqResMessage = _reflection.GeneratedProtocolMessageType('ReqResMessage', (_message.Message,), {

  'DictNotesEntry' : _reflection.GeneratedProtocolMessageType('DictNotesEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQRESMESSAGE_DICTNOTESENTRY,
    '__module__' : 'transmission_pb2'
    # @@protoc_insertion_point(class_scope:transmission.ReqResMessage.DictNotesEntry)
    })
  ,
  'DESCRIPTOR' : _REQRESMESSAGE,
  '__module__' : 'transmission_pb2'
  # @@protoc_insertion_point(class_scope:transmission.ReqResMessage)
  })
_sym_db.RegisterMessage(ReqResMessage)
_sym_db.RegisterMessage(ReqResMessage.DictNotesEntry)


_REQRESMESSAGE_DICTNOTESENTRY._options = None

_TRANSMISSION = _descriptor.ServiceDescriptor(
  name='Transmission',
  full_name='transmission.Transmission',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=706,
  serialized_end=788,
  methods=[
  _descriptor.MethodDescriptor(
    name='comm',
    full_name='transmission.Transmission.comm',
    index=0,
    containing_service=None,
    input_type=_REQRESMESSAGE,
    output_type=_REQRESMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSMISSION)

DESCRIPTOR.services_by_name['Transmission'] = _TRANSMISSION

# @@protoc_insertion_point(module_scope)
